/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSurveysRouteImport } from './routes/_app.surveys'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPayoutRouteImport } from './routes/_app.payout'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppTrainingsIndexRouteImport } from './routes/_app.trainings.index'
import { Route as STestTokenRouteImport } from './routes/s.test.$token'
import { Route as SSurveyL3TokenRouteImport } from './routes/s.survey-l3.$token'
import { Route as SSurveyL1TokenRouteImport } from './routes/s.survey-l1.$token'
import { Route as SCertificateTokenRouteImport } from './routes/s.certificate.$token'
import { Route as AppTrainingsNewRouteImport } from './routes/_app.trainings.new'
import { Route as AppTrainingsIdRouteImport } from './routes/_app.trainings.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysRoute = AppSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPayoutRoute = AppPayoutRouteImport.update({
  id: '/payout',
  path: '/payout',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingsIndexRoute = AppTrainingsIndexRouteImport.update({
  id: '/trainings/',
  path: '/trainings/',
  getParentRoute: () => AppRoute,
} as any)
const STestTokenRoute = STestTokenRouteImport.update({
  id: '/s/test/$token',
  path: '/s/test/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SSurveyL3TokenRoute = SSurveyL3TokenRouteImport.update({
  id: '/s/survey-l3/$token',
  path: '/s/survey-l3/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SSurveyL1TokenRoute = SSurveyL1TokenRouteImport.update({
  id: '/s/survey-l1/$token',
  path: '/s/survey-l1/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SCertificateTokenRoute = SCertificateTokenRouteImport.update({
  id: '/s/certificate/$token',
  path: '/s/certificate/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrainingsNewRoute = AppTrainingsNewRouteImport.update({
  id: '/trainings/new',
  path: '/trainings/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingsIdRoute = AppTrainingsIdRouteImport.update({
  id: '/trainings/$id',
  path: '/trainings/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/payout': typeof AppPayoutRoute
  '/settings': typeof AppSettingsRoute
  '/surveys': typeof AppSurveysRoute
  '/team': typeof AppTeamRoute
  '/trainings/$id': typeof AppTrainingsIdRoute
  '/trainings/new': typeof AppTrainingsNewRoute
  '/s/certificate/$token': typeof SCertificateTokenRoute
  '/s/survey-l1/$token': typeof SSurveyL1TokenRoute
  '/s/survey-l3/$token': typeof SSurveyL3TokenRoute
  '/s/test/$token': typeof STestTokenRoute
  '/trainings/': typeof AppTrainingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/payout': typeof AppPayoutRoute
  '/settings': typeof AppSettingsRoute
  '/surveys': typeof AppSurveysRoute
  '/team': typeof AppTeamRoute
  '/trainings/$id': typeof AppTrainingsIdRoute
  '/trainings/new': typeof AppTrainingsNewRoute
  '/s/certificate/$token': typeof SCertificateTokenRoute
  '/s/survey-l1/$token': typeof SSurveyL1TokenRoute
  '/s/survey-l3/$token': typeof SSurveyL3TokenRoute
  '/s/test/$token': typeof STestTokenRoute
  '/trainings': typeof AppTrainingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/payout': typeof AppPayoutRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/surveys': typeof AppSurveysRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/trainings/$id': typeof AppTrainingsIdRoute
  '/_app/trainings/new': typeof AppTrainingsNewRoute
  '/s/certificate/$token': typeof SCertificateTokenRoute
  '/s/survey-l1/$token': typeof SSurveyL1TokenRoute
  '/s/survey-l3/$token': typeof SSurveyL3TokenRoute
  '/s/test/$token': typeof STestTokenRoute
  '/_app/trainings/': typeof AppTrainingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/login'
    | '/calendar'
    | '/dashboard'
    | '/payout'
    | '/settings'
    | '/surveys'
    | '/team'
    | '/trainings/$id'
    | '/trainings/new'
    | '/s/certificate/$token'
    | '/s/survey-l1/$token'
    | '/s/survey-l3/$token'
    | '/s/test/$token'
    | '/trainings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/login'
    | '/calendar'
    | '/dashboard'
    | '/payout'
    | '/settings'
    | '/surveys'
    | '/team'
    | '/trainings/$id'
    | '/trainings/new'
    | '/s/certificate/$token'
    | '/s/survey-l1/$token'
    | '/s/survey-l3/$token'
    | '/s/test/$token'
    | '/trainings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/activate'
    | '/login'
    | '/_app/calendar'
    | '/_app/dashboard'
    | '/_app/payout'
    | '/_app/settings'
    | '/_app/surveys'
    | '/_app/team'
    | '/_app/trainings/$id'
    | '/_app/trainings/new'
    | '/s/certificate/$token'
    | '/s/survey-l1/$token'
    | '/s/survey-l3/$token'
    | '/s/test/$token'
    | '/_app/trainings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ActivateRoute: typeof ActivateRoute
  LoginRoute: typeof LoginRoute
  SCertificateTokenRoute: typeof SCertificateTokenRoute
  SSurveyL1TokenRoute: typeof SSurveyL1TokenRoute
  SSurveyL3TokenRoute: typeof SSurveyL3TokenRoute
  STestTokenRoute: typeof STestTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surveys': {
      id: '/_app/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof AppSurveysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payout': {
      id: '/_app/payout'
      path: '/payout'
      fullPath: '/payout'
      preLoaderRoute: typeof AppPayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trainings/': {
      id: '/_app/trainings/'
      path: '/trainings'
      fullPath: '/trainings/'
      preLoaderRoute: typeof AppTrainingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/s/test/$token': {
      id: '/s/test/$token'
      path: '/s/test/$token'
      fullPath: '/s/test/$token'
      preLoaderRoute: typeof STestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/survey-l3/$token': {
      id: '/s/survey-l3/$token'
      path: '/s/survey-l3/$token'
      fullPath: '/s/survey-l3/$token'
      preLoaderRoute: typeof SSurveyL3TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/survey-l1/$token': {
      id: '/s/survey-l1/$token'
      path: '/s/survey-l1/$token'
      fullPath: '/s/survey-l1/$token'
      preLoaderRoute: typeof SSurveyL1TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/certificate/$token': {
      id: '/s/certificate/$token'
      path: '/s/certificate/$token'
      fullPath: '/s/certificate/$token'
      preLoaderRoute: typeof SCertificateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trainings/new': {
      id: '/_app/trainings/new'
      path: '/trainings/new'
      fullPath: '/trainings/new'
      preLoaderRoute: typeof AppTrainingsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trainings/$id': {
      id: '/_app/trainings/$id'
      path: '/trainings/$id'
      fullPath: '/trainings/$id'
      preLoaderRoute: typeof AppTrainingsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPayoutRoute: typeof AppPayoutRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSurveysRoute: typeof AppSurveysRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTrainingsIdRoute: typeof AppTrainingsIdRoute
  AppTrainingsNewRoute: typeof AppTrainingsNewRoute
  AppTrainingsIndexRoute: typeof AppTrainingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPayoutRoute: AppPayoutRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSurveysRoute: AppSurveysRoute,
  AppTeamRoute: AppTeamRoute,
  AppTrainingsIdRoute: AppTrainingsIdRoute,
  AppTrainingsNewRoute: AppTrainingsNewRoute,
  AppTrainingsIndexRoute: AppTrainingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ActivateRoute: ActivateRoute,
  LoginRoute: LoginRoute,
  SCertificateTokenRoute: SCertificateTokenRoute,
  SSurveyL1TokenRoute: SSurveyL1TokenRoute,
  SSurveyL3TokenRoute: SSurveyL3TokenRoute,
  STestTokenRoute: STestTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
